#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the time_delta function below.
def time_delta(t1, t2):
    # Complete the time_delta function below.
    from datetime import datetime
    
    fmt = "%a %d %b %Y %H:%M:%S %z"
    
    # Fix missing space before timezone (important for some test cases)
    if t1[-5] != ' ':
        t1 = t1[:-5] + ' ' + t1[-5:]
    if t2[-5] != ' ':
        t2 = t2[:-5] + ' ' + t2[-5:]
    
    d1 = datetime.strptime(t1, fmt)
    d2 = datetime.strptime(t2, fmt)
    
    return str(abs(int((d1 - d2).total_seconds())))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        t1 = input()

        t2 = input()

        delta = time_delta(t1, t2)

        fptr.write(delta + '\n')

    fptr.close()
